#!/usr/bin/env python3

"""
A quick script to send a toot
"""

import sys
from mastodon import Mastodon


try:
    sys.argv[1]
except IndexError as err:
    print("Error: Did you forget to include a message?")

#   Set up Mastodon
mastodon = Mastodon(access_token="token.secret", api_base_url="https://fosstodon.org/")

mastodon.status_post(sys.argv[1])
